server.port=8080
spring.application.name=EnterpriseBackSystem

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.group-configs[0].group=demo
springdoc.group-configs[0].paths-to-match[0]=/api/demo/**
